/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTreeV2: typeof import('element-plus/es')['ElTreeV2']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HynCronExpression: typeof import('./../../../packages/hyn-ui/src/HynCronExpression/index.vue')['default']
    HynDeptSelect: typeof import('./../../../packages/hyn-ui/src/HynDeptSelect/index.vue')['default']
    HynDialog: typeof import('./../../../packages/hyn-ui/src/HynDialog/index.vue')['default']
    HynEntityPicker: typeof import('./../../../packages/hyn-ui/src/HynEntityPicker/index.vue')['default']
    HynForm: typeof import('./../../../packages/hyn-ui/src/HynForm/index.vue')['default']
    HynRemoteSelect: typeof import('./../../../packages/hyn-ui/src/HynRemoteSelect/index.vue')['default']
    HynTable: typeof import('./../../../packages/hyn-ui/src/HynTable/index.vue')['default']
    HynTableDialog: typeof import('./../../../packages/hyn-ui/src/HynTableDialog/index.vue')['default']
    HynTreeSelect: typeof import('./../../../packages/hyn-ui/src/HynTreeSelect/index.vue')['default']
    HynVirtualTable: typeof import('./../../../packages/hyn-ui/src/HynVirtualTable/index.vue')['default']
    HynVirtualTreeTable: typeof import('./../../../packages/hyn-ui/src/HynVirtualTreeTable/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
